-- Tabela Cliente
CREATE TABLE Cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    contato VARCHAR2(15),
    cep VARCHAR2(10),
    bairro VARCHAR2(50),
    cidade VARCHAR2(50),
    estado VARCHAR2(2),
    logradouro VARCHAR2(100),
    numero VARCHAR2(10),
    complemento VARCHAR2(50),
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N'))
);

-- Tabela Animal
CREATE TABLE Animal (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES Cliente(id) ON DELETE CASCADE,
    nome VARCHAR2(50) NOT NULL,
    raca VARCHAR2(50),
    cor VARCHAR2(30),
    idade NUMBER,
    especie VARCHAR2(50),
    problemas_saude CLOB,
    nascimento DATE,
    foto BLOB
);

-- Tabela Agenda
CREATE TABLE Agenda (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES Cliente(id) ON DELETE CASCADE,
    animal_id NUMBER NOT NULL REFERENCES Animal(id) ON DELETE CASCADE,
    data_hora TIMESTAMP NOT NULL,
    descricao CLOB,
    valor NUMBER(10, 2),
    retirar CHAR(1) DEFAULT 'N' CHECK (retirar IN ('S', 'N')),
    perfume VARCHAR2(50),
    sexo VARCHAR2(10)
);

-- Tabela Consulta
CREATE TABLE Consulta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES Cliente(id) ON DELETE CASCADE,
    animal_id NUMBER NOT NULL REFERENCES Animal(id) ON DELETE CASCADE,
    contato VARCHAR2(15),
    data_hora TIMESTAMP NOT NULL,
    servico_realizado CLOB,
    observacoes CLOB,
    tipo_atendimento VARCHAR2(50),
    exames CLOB,
    valor_consulta NUMBER(10, 2),
    valor_vacina NUMBER(10, 2),
    valor_vermifugo NUMBER(10, 2),
    data_vacina DATE,
    data_retorno DATE
);

-- Tabela Rastreio
CREATE TABLE Rastreio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES Cliente(id) ON DELETE CASCADE,
    animal_id NUMBER NOT NULL REFERENCES Animal(id) ON DELETE CASCADE,
    etapa VARCHAR2(100)
);

-- Tabela Login
CREATE TABLE Login (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL
);

-- Tabela Administrador
CREATE TABLE Administrador (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    login_id NUMBER UNIQUE REFERENCES Login(id) ON DELETE CASCADE
);

-- Tabela Veterinaria
CREATE TABLE Veterinaria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    login_id NUMBER UNIQUE REFERENCES Login(id) ON DELETE CASCADE
);
